### ISSUE TITLE
Not working with IntelliJ 14

### ISSUE THREAD

**Issue by hhimanshu** [dboissier/jenkins-control-plugin#102]
I tried the steps mentioned in README, I see following, what am I missing?

<img width="1231" alt="screen shot 2015-11-11 at 11 25 24 am" src="https://cloud.githubusercontent.com/assets/6589036/11100606/1d3d9b10-8867-11e5-93c2-ccce2b77ed8f.png">
<img width="525" alt="screen shot 2015-11-11 at 11 25 41 am" src="https://cloud.githubusercontent.com/assets/6589036/11100607/1d3e01a4-8867-11e5-8357-48c7b6eb0454.png">
<img width="742" alt="screen shot 2015-11-11 at 11 25 48 am" src="https://cloud.githubusercontent.com/assets/6589036/11100605/1d3cea1c-8867-11e5-8b35-35079ff8fb6b.png">

**Comment by cezary-butler** [comment]
It seems that plugin build with intellij 15 sdk does not work on intellij idea 14.
For now, option that would work is using version 0.9.2 which has been built with older SDK.
I'll try to find other solution, but this will take time.

**Comment by hhimanshu** [comment]
How can I get 0.9.2 version?

**Comment by cezary-butler** [comment]
Generally here: https://plugins.jetbrains.com/plugin/6110?pr= you can find most of plugin versions.
I don't see 0.9.2 here, I don't know reason for that, but 0.9.1 should also work.

**Comment by hhimanshu** [comment]
What are installation steps? I downloaded, provided zip from Plugins -> install from Disk (did not work). Then I unzipped and gave the jar (did not work)

I am not sure what is going wrong

**Comment by cezary-butler** [comment]
_Install from disk_ should just work.
Uninstalling previously installed version might be necessary.

**Comment by cezary-butler** [comment]
_0.9.2_ and _0.9.3_ are also there and should be compatibile with Intellij 14.
To see them you need to click _show all updates_,
Personally I would recommend using 0.9.3 which you can download direclty [here](https://plugins.jetbrains.com/plugin/download?pr=&updateId=22079).
Please use one of those.

**Comment by dboissier** [comment]
Hi @hhimanshu ,

@cezary-butler made robust fix for Idea 14 / 15 compatibility issue

 Could you please test this [SNAPSHOT](https://github.com/dboissier/jenkins-control-plugin/raw/master/snapshot/jenkins-control-plugin-0.9.4-SNAPSHOT-distribution.zip) and tell me if it works on your IDE?

Thanks.

**Comment by hhimanshu** [comment]
@dboissier @cezary-butler , this works for me. Thanks a lot for your help
