### ISSUE TITLE
Support for Jenkins 2

### ISSUE THREAD

**Issue by kdawgwilk** [dboissier/jenkins-control-plugin#126]
I know you don't support Jenkins 2, per the README but I figured since Jenkins 2 has now hit LTS it might be a good time to start the update process.  I am willing to help make this happen and wondered what barriers there are to get this running with Jenkins 2?

**Comment by cezary-butler** [comment]
It's good to hear that someone is willing to put some time into plugin development.
As I see that, this plugin is only one small step from being abandoned.
David only has time to fix most severe bugs, and I have almost no time at all that I can use for further plugin development.

I see only one important barrier that keeps plugin from working with Jenkins 2. 
Special version of network communication classes would have to be implemented to work with Jenkins 2.
There may be some structure differences which may be difficult to map to model created to work with older version of Jenkins - this should be looked at closely. 
Classes which currently are involved into communication (this should be good place to start):
* `org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser`
* `org.codinjutsu.tools.jenkins.logic.RequestManager`
* `org.codinjutsu.tools.jenkins.logic.RssParser`

If you have any problems with plugin development, let me know, I thik I may be able to help you.

**Comment by kdawgwilk** [comment]
👍 Alright I will see what I can do, I am in the process of switching from TeamCity to Jenkins and still have some learning to do but I think I should be able to figure something out.

**Comment by dboissier** [comment]
Hi,

thanks to Github contributors, new builds for Idea-15 and Idea-2016 are available on the home page of the project.

Please tell me whether it fixes the encountered issue.

Thanks for your patience.
