### ISSUE TITLE
Missing or bad crumb data

### ISSUE THREAD

**Issue by jdliferay** [dboissier/jenkins-control-plugin#134]
Hi,
i've installed jenkins server and run it. i've installed kenjins control plugin on intellij .
try to configure jenkins settings --> test connection gives me [Missing or bad crumb data]
i am using intellij 2016.3 and jenkins server 2.19.4

thanks a lot.

**Comment by azharsikander** [comment]
BTW, I am also running into same issue.

**Comment by jdliferay** [comment]
i am using jenkins 2.19.4 version

**Comment by jboffel** [comment]
Same problem, even I provide the crumb data it does not change anything...

**Comment by pcornelissen** [comment]
Jenkins 2.32.2 => Still bad crumb data...

**Comment by dboissier** [comment]
Hi,

thanks to Github contributors, new builds for Idea-15 and Idea-2016 are available on the home page of the project.

Please tell me whether it fixes the encountered issue.

Thanks for your patience.

**Comment by pcornelissen** [comment]
just updated the plugin via the plugin repository in intelliJ and the problem remains

**Comment by jdliferay** [comment]
tried to update the plugin version and all work like a charm, thanks .

**Comment by pcornelissen** [comment]
Just to be sure I even installed the version from the zip at github and it still complains about missing crumb data

**Comment by dboissier** [comment]
Hi @pcornelissen,

Is CRSF set in your Jenkins server ?

**Comment by pcornelissen** [comment]
yes, csrf is enabled with the default crumb generator, the proxy mode setting is off

**Comment by dboissier** [comment]
Ok. You may need to get the crumb with the following URL
```
http://<jenkins_url>/crumbIssuer/api/json?tree=crumb
```
And put the **crumb** value in the Jenkins plugin settings.

Please tell if it works.

**Comment by jdliferay** [comment]
Or you can try this URL http://<jenkins_url>/crumbIssuer/api/xml

**Comment by pcornelissen** [comment]
Oh I think I tried the api token today not the crumb data...
But you could make this easier for devs if you'd use the already configured jenkins URL and put abutton or link somewhere in the settings that leads to the crumb data in jenkins. This way it's more "in your face" and the danger of missing this part of the documentation is smaller.

**Comment by amit-appalladium** [comment]
Its started working now for jenkins 2.x with crum data.
if it can also support google authentication configured for jenkins it will be really awesome !!!

**Comment by dboissier** [comment]
@amit-appalladium this is a good idea. Will make it for the next release.

Thx

**Comment by techinsight** [comment]
jenkins plugin  v0.10.2016 not work on Android Studio.
v0.10.15 cannot be installed.

**Comment by Amrkamel1** [comment]
@dboissier 

im facing same through all data are correct 

![image](https://user-images.githubusercontent.com/32042806/74970808-54b3a480-541f-11ea-9cb1-da39fe141da1.png)

![image](https://user-images.githubusercontent.com/32042806/74970798-50878700-541f-11ea-8784-c5776bef8c4b.png)

![image](https://user-images.githubusercontent.com/32042806/74970865-6eed8280-541f-11ea-887b-61e022386dbc.png)

**Comment by mrlee23** [comment]
@dboissier

I have same problem too

![스크린샷 2020-02-21 10 16 08](https://user-images.githubusercontent.com/6349609/74995154-620a7680-5493-11ea-88e8-682a8197229b.png)

![스크린샷 2020-02-21 10 14 52](https://user-images.githubusercontent.com/6349609/74995163-6fbffc00-5493-11ea-864e-8ab2e95eafb7.png)

**Comment by xros** [comment]
@Amrkamel1 @mrlee23 same problem here...
Solved yet?

pycharm 2019.1.3
jenkins plugin in pycharm v0.11.0
Jenkins server ver. 2.204.2

**Comment by MCMicS** [comment]
@xros Since Jenkins 2.176 the CSRF handling was improved. The the crumb not work anymore with different session.
We could change the code to handle an own session. But i think it is better to use an API token for authentication the plugin.
To do this do following:
1. Got to your user setting: http://<jenkinsUrl>:8080/user/<user>/configure
2. Add New API Token for Jenkins Plugin
3. Use this API Token as your Password

see https://github.com/MCMicS/jenkins-control-plugin/issues/173

If you have any questions please let me know.

**Comment by hbetts3** [comment]
> @xros Since Jenkins 2.176 the CSRF handling was improved. The the crumb not work anymore with different session.
> We could change the code to handle an own session. But i think it is better to use an API token for authenticate the plugin.
> To do this do following:
> 
> 1. Got to your user setting: http://:8080/user//configure
> 2. Add New API Token for Jenkins Plugin
> 3. Use this API Token as your Password
> 
> see #173
> 
> If you have any questions please let me know.

While this works... it bypasses the fundamental issue of the use of CSRF prevention on Jenkins. You have to turn it off ... no bueno.

**Comment by MCMicS** [comment]
No
CSRF is still activated. The CSRF will be reduced to websessions only and not to API Consumer like scripts or plugins.

But if you need an CSRF protection please reopen the issue (or create new one) with this request and we can schedule it

**Comment by xinatcg** [comment]
> @xros Since Jenkins 2.176 the CSRF handling was improved. The the crumb not work anymore with different session.
> We could change the code to handle an own session. But i think it is better to use an API token for authenticate the plugin.
> To do this do following:
> 
> 1. Got to your user setting: http://:8080/user//configure
> 2. Add New API Token for Jenkins Plugin
> 3. Use this API Token as your Password
> 
> see #173
> 
> If you have any questions please let me know.

Thanks it works

**Comment by VNYoeri** [comment]
> @xros Since Jenkins 2.176 the CSRF handling was improved. The the crumb not work anymore with different session.
> We could change the code to handle an own session. But i think it is better to use an API token for authenticate the plugin.
> To do this do following:
> 
> 1. Got to your user setting: http://:8080/user//configure
> 2. Add New API Token for Jenkins Plugin
> 3. Use this API Token as your Password
> 
> see #173
> 
> If you have any questions please let me know.

small improvement:  `http://<jenkins_url>/user/<username>/configure`

**Comment by rodude123** [comment]
> @xros Since Jenkins 2.176 the CSRF handling was improved. The the crumb not work anymore with different session.
> We could change the code to handle an own session. But i think it is better to use an API token for authenticate the plugin.
> To do this do following:
> 
>     1. Got to your user setting: http://:8080/user//configure
> 
>     2. Add New API Token for Jenkins Plugin
> 
>     3. Use this API Token as your Password
> 
> 
> see #173
> 
> If you have any questions please let me know.

Can confirm this works on V2.235.4
