### ISSUE TITLE
Crumb not work anymore with latest Jenkins LTS

### ISSUE THREAD

**Issue by MCMicS** [dboissier/jenkins-control-plugin#173]
Due better CSRF handling with latest JEnkisn version the plugin not work anymore.

> org.codinjutsu.tools.jenkins.security.AuthenticationException: CSRF enabled -> Missing or bad crumb data
> 	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.checkResponse(DefaultSecurityClient.java:150)
> 	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.runMethod(DefaultSecurityClient.java:124)
> 	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.execute(DefaultSecurityClient.java:68)
> 	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:123)
> 	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:249)
> 

see: https://jenkins.io/doc/upgrade-guide/2.176/

**Comment by Kshitiz-Sharma** [comment]
+1 for this issue. I've referred to issue #123 but still getting the problem. This seems to be reccuring with the latest version of jenkins

**Comment by MCMicS** [comment]
Fix is to use API Token instead. I think no change is needed for that.

**Comment by Kisty** [comment]
I have an API token but how do you use it with the plugin?

**Comment by MCMicS** [comment]
you can use it as you password and then you didn't need a crumb
Let me know if you need further help

**Comment by duykieu** [comment]
No! Using API Token still not authenticated

**Comment by MCMicS** [comment]
@duykieu Do you get an error?
